// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using culturalEvents.Shared.Infrastructure.Database;

#nullable disable

namespace culturalEvents.Shared.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    partial class AppDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid")
                        .HasColumnName("permissions_id");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid")
                        .HasColumnName("roles_id");

                    b.HasKey("PermissionsId", "RolesId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("RolesId")
                        .HasDatabaseName("ix_role_permissions_roles_id");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_user_roles");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_user_roles_users_id");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.CulturalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UtcDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utc_date");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_events_artist_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_events_venue_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Offering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("price");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_offerings");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_offerings_provider_id");

                    b.ToTable("offerings", (string)null);
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<Guid?>("CulturalEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("cultural_event_id");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("UtcCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utc_created_at");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_orders_artist_id");

                    b.HasIndex("CulturalEventId")
                        .HasDatabaseName("ix_orders_cultural_event_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_orders_event_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_orders_provider_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("OfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("offering_id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OfferingId")
                        .HasDatabaseName("ix_order_items_offering_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("TicketSeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_seat_id");

                    b.Property<DateTime>("UtcReservationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utc_reservation_date");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_tickets_event_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.TicketSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("seat_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("VenueId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_seats_venue_id_seat_number");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("RentalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("rental_price");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_venues_name");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("culturalEvents.Shared.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permissions_id");

                    b.HasOne("culturalEvents.Shared.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_roles_id");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("culturalEvents.Shared.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_roles_id");

                    b.HasOne("culturalEvents.Shared.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_users_id");
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.CulturalEvent", b =>
                {
                    b.HasOne("culturalEvents.Shared.Domain.User", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_users_artist_id");

                    b.HasOne("culturalEvents.Shared.Domain.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .HasConstraintName("fk_events_venues_venue_id");

                    b.Navigation("Artist");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Offering", b =>
                {
                    b.HasOne("culturalEvents.Shared.Domain.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_offerings_users_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Order", b =>
                {
                    b.HasOne("culturalEvents.Shared.Domain.User", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_users_artist_id");

                    b.HasOne("culturalEvents.Shared.Domain.CulturalEvent", null)
                        .WithMany("Orders")
                        .HasForeignKey("CulturalEventId")
                        .HasConstraintName("fk_orders_events_cultural_event_id");

                    b.HasOne("culturalEvents.Shared.Domain.CulturalEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .HasConstraintName("fk_orders_events_event_id");

                    b.HasOne("culturalEvents.Shared.Domain.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_users_provider_id");

                    b.Navigation("Artist");

                    b.Navigation("Event");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.OrderItem", b =>
                {
                    b.HasOne("culturalEvents.Shared.Domain.Offering", "Offering")
                        .WithMany()
                        .HasForeignKey("OfferingId")
                        .HasConstraintName("fk_order_items_offerings_offering_id");

                    b.HasOne("culturalEvents.Shared.Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Offering");
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Ticket", b =>
                {
                    b.HasOne("culturalEvents.Shared.Domain.CulturalEvent", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .HasConstraintName("fk_tickets_events_event_id");

                    b.HasOne("culturalEvents.Shared.Domain.TicketSeat", "TicketSeat")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_seats_id");

                    b.Navigation("Event");

                    b.Navigation("TicketSeat");
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.TicketSeat", b =>
                {
                    b.HasOne("culturalEvents.Shared.Domain.Venue", "Venue")
                        .WithMany("Seats")
                        .HasForeignKey("VenueId")
                        .HasConstraintName("fk_seats_venues_venue_id");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.CulturalEvent", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("culturalEvents.Shared.Domain.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
